from tkinter import ttk, PhotoImage

from utils.BuildResolve import resolve_route


class Header:
    def __init__(self, root):
        self.root = root
        self.header = self.crear_header()

    def crear_header(self):
        frame = ttk.Frame(self.root, width=300, height=200)
        frame.grid(row=0, column=0, columnspan=2)

        # frame = ttk.Frame(self.root, width=300, height=200, bg="lightblue")
        # frame.pack(padx=20, pady=20)

        logo = PhotoImage(file=resolve_route('assets/logo_icon.png'))
        logo = logo.subsample(4, 4)
        logo_label = ttk.Label(frame, image=logo)
        logo_label.image = logo
        logo_label.grid(row=0, column=0, padx=20, pady=10, sticky="w")

        description = "Tool to convert and translate the documentation generated by MO4D to a Word"
        description_label = ttk.Label(frame, text=description)
        description_label.grid(row=1, column=0, padx=20, pady=10, sticky="w")

        return frame
